Sub Main

  Call ResetParameters
  Call AddStringParameter ("TopSignal"         , "True"  )
  Call AddStringParameter ("Mid1"              , "False" )
  Call AddStringParameter ("Mid2"              , "False" )
  Call AddStringParameter ("Mid3"              , "False" )
  Call AddStringParameter ("Mid4"              , "False" )
  Call AddStringParameter ("Mid5"              , "False" )
  Call AddStringParameter ("Mid6"              , "False" )
  Call AddStringParameter ("Mid7"              , "False" )
  Call AddStringParameter ("Mid8"              , "False" )
  Call AddStringParameter ("Mid9"              , "False" )
  Call AddStringParameter ("Mid10"             , "False" )
  Call AddStringParameter ("Mid11"             , "False" )
  Call AddStringParameter ("Mid12"             , "False" )
  Call AddStringParameter ("Mid13"             , "False" )
  Call AddStringParameter ("Mid14"             , "False" )
  Call AddStringParameter ("BottomSignal"      , "False" )
  Call AddStringParameter ("TopOverlay"        , "True"  )
  Call AddStringParameter ("BottomOverlay"     , "False" )
  Call AddStringParameter ("TopPaste"          , "False" )
  Call AddStringParameter ("BottomPaste"       , "False" )
  Call AddStringParameter ("TopSolder"         , "False" )
  Call AddStringParameter ("BottomSolder"      , "False" )
  Call AddStringParameter ("Plane1"            , "False" )
  Call AddStringParameter ("Plane2"            , "False" )
  Call AddStringParameter ("Plane3"            , "False" )
  Call AddStringParameter ("Plane4"            , "False" )
  Call AddStringParameter ("DrillGuide"        , "False" )
  Call AddStringParameter ("KeepOut"           , "True"  )
  Call AddStringParameter ("Mechanical1"       , "True"  )
  Call AddStringParameter ("Mechanical2"       , "False" )
  Call AddStringParameter ("Mechanical3"       , "False" )
  Call AddStringParameter ("Mechanical4"       , "False" )
  Call AddStringParameter ("DrillDrawing"      , "False" )
  Call AddStringParameter ("MultiLayer"        , "True"  )

  Call RunProcess ("Pcb:DocumentPreferences")

End Sub